-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 29, 2024 at 04:42 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `peter`
--

-- --------------------------------------------------------

--
-- Table structure for table `menus`
--

CREATE TABLE `menus` (
  `id` int(11) NOT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `flavors` varchar(255) DEFAULT NULL,
  `effects` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `imageUrl` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `menus`
--

INSERT INTO `menus` (`id`, `vendor_id`, `name`, `category`, `flavors`, `effects`, `description`, `imageUrl`) VALUES
(1, 1, 'Black Runtz', 'Flower', '', '', 'New new', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-FPJ9OGVc72ncdCD0IqsQuny4ae0LBhLbvUC3C5eB.png'),
(2, 1, 'Lemon Cherry Gelato - Shake', 'Flower', 'Fruit, Sweet, Tropical', 'Happy, Relaxed', 'Lemon Cherry Gelato is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Sunset Sherbet X Girl Scout Cookies X another unknown strain. The perfect tasty bud for any relaxed night spent at home.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-EtjaxBmCbCBS5mBT4yiCDAXrsN0sUVOYv3fN58Nm.png'),
(3, 1, 'Ice Cream Cake', 'Flower', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-O2XaDlff19ostaWVejbasTKskEaEl5e6UvkK4bLs.jpeg'),
(4, 1, 'Skittlez', 'Flower', '', '', 'New new', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-HTkz8JVwrGM2vyjfCvYtdbR9irIcoAtzSTdncPAh.jpeg'),
(5, 1, 'Runtz', 'Flower', 'Fruit, Pineapple, Spicy/Herbal', '', 'Runtz is an evenly balanced hybrid strain (50% indica/50% sativa) created through a delicious cross of the infamous Zkittlez X Gelato strains. Named for the iconic candy, Runtz brings on a super delicious fruity flavor.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-xzds7G0tyqW3ZGEHkDzE3DuXUMi5K9QYUzClRdDK.jpeg'),
(6, 1, 'Oreoz', 'Flower', 'Diesel, Nutty, Spicy/Herbal', 'Happy, Uplifted', 'Oreoz is an indica dominant hybrid strain (70% indica/30% sativa) created through crossing the delicious Cookies N Cream X Secret Weapon strains. Named for its super delicious flavor, Oreoz is a great choice for any indica lover.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-og8wslWGsFURs7VMp6XyJrojodQDWigoL9172rkB.jpeg'),
(7, 1, 'Frosted Cherries', 'Flower', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-yPU8lDb9gAxM6jw59V7f2DwvKM9l9ZD1r6DEsV8o.jpeg'),
(8, 1, 'Cheetah Piss', 'Flower', 'Fruit, Sweet, Lemon', 'Focused, Creative, Aroused', 'Cheetah Piss is a rare evenly balanced hybrid strain (50% indica/50% sativa) created through crossing the iconic Lemonnade X Gelato 42 X London Poundcake 97 strains. Made as a homage to the infamous “Cat Piss” strain, Cheetah Piss is super potent.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-SRk02IOQmTsCLrM9jmVl0zCR1L8iNH63udomOfSl.jpeg'),
(9, 1, 'Gelatti', 'Flower', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-QFyAInEUNWhSejFwosoBOdVlCIJv1qkepHOcW0Ha.jpeg'),
(10, 1, 'Gelato 47 (Mochi)', 'Flower', '', '', 'New new', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-JfhZXsXR2qTYleAdsAuZZSDigVku8MbFPJ7uo9Kv.jpeg'),
(11, 1, 'Gelato 41', 'Flower', '', '', 'New new', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-wApSgsoaJJS6sSyGi3THXkQKEXb7RbNqCEBhoqPY.jpeg'),
(12, 1, 'Sour Skittles', 'Flower', '', '', 'New new', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-uHqLCfdPzFWzVHyD57r6p6GNHRtODiXiBEAiF3Gn.jpeg'),
(13, 1, 'Sour Diesel', 'Flower', 'Citrus, Diesel, Skunk', 'Creative, Euphoric, Happy', 'Sour Diesel, otherwise known as \"Sour D\" or \"Sour Deez\" is a sativa dominant hybrid strain with a 90:10 sativa/indica ratio. The origin of Sour Diesel is frequently debated within the marijuana community.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-OgJEUGi5dtQUk7lUTHRkIFhS9D23evCw27y79AAA.jpeg'),
(14, 1, 'Hit It! OG - Dispensary 31%+', 'Flower', '', '', 'new new', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-caX9O7equoLd8NpZyNknd1lKChJx1AWRe1HJow7W.jpeg'),
(15, 1, 'Hit It! UFO Runtz - Dispensary 31%+', 'Flower', '', '', 'Dispensary', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-Op0MYOrCjfanPil4kPk9FQk3C0rRBCH4WN9mvwwh.jpeg'),
(16, 1, 'Hit It! Pink Runtz - Dispensary 30%', 'Flower', '', '', 'Pink Runtz is a rare evenly balanced hybrid strain (50% indica/50% sativa) created either as a phenotype of the infamous Runtz strain, a Zkittlez X Gelato cross.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-qq4KaHbBxfqftNKf1tCLiyput2RwUcYYM1UrFbyV.png'),
(17, 1, 'Hit It! Lemon Cherry Gelato - Dispensary 37%+', 'Flower', '', '', 'Dispensary', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-Bh9k4rzGkuIDn7s57LekRy647eyS719a1JdY9Qwl.jpeg'),
(18, 1, 'Jayne Pre-rolls (7 pack) 2.8g - Sativa', 'Preroll', '', '', 'California quality product. Sativa and Hybrid Indica available.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-ItUdITQrbaK1ODrnoFnDIgnAvxxVufzKGwdohsh0.jpg'),
(19, 1, 'Gold Coast Clear Carts', 'Concentrates', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-4vc1HLwsbhWKcj3itDaQgKjDbb7XZxRPR56HqyP5.jpg'),
(20, 1, 'Potters Live Resin Carts - Sativa', 'Concentrates', '', '', 'Licensed California carts.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-17kzCD21SJOi8SM3EXdEXbQ4KjjqHrTM2pPDFCfA.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-17kzCD21SJOi8SM3EXdEXbQ4KjjqHrTM2pPDFCfA.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-rO9z8JZm9qHK1P2MTHPzEZIXfrZAx0NsVoy3eY1S.png'),
(21, 1, 'Potters Live Resin Carts - Hybrid', 'Concentrates', '', '', 'Licensed California carts.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-6ORzpmnJ45ZSNoU2C8jHtb2zNpufN6bnRIy5t5R4.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-6ORzpmnJ45ZSNoU2C8jHtb2zNpufN6bnRIy5t5R4.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-Bt6EFiShBV3z7TjDGdtgnfrgD1EfFnfZ9WH8xVq2.png'),
(22, 1, 'Slurricane Badder', 'Concentrates', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-0sMGeQwwJ4AooVFWwdup5peUjp7VUrK82cQv1sKX.png'),
(23, 1, 'Lemon Squeeze Badder', 'Concentrates', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-0sMGeQwwJ4AooVFWwdup5peUjp7VUrK82cQv1sKX.png'),
(24, 1, 'Sugar - Do-Si-Dos', 'Concentrates', '', '', 'New', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-OD47NcTgJs39llWzYFVAhAnxWyzBFf5jD5FVcew9.jpeg'),
(25, 1, 'Delights Gummies - 100mg', 'Edible', '', '', 'Licensed edibles', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-0sMGeQwwJ4AooVFWwdup5peUjp7VUrK82cQv1sKX.png'),
(26, 1, 'Highatus Pomberry 10-pack 100mg', 'Edible', '', '', 'Dispensary', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-pGeAI4qCHmVE6Q7abNVxvONkL6rezF51kDgn6Vdb.v1671570813.jpg, https://leafedout.com/storage/usercontent/photos/LeafedOut-mWjFu1jxirLNRAFGZdImORNRAD4yCVgqlQScwHrh.jpeg'),
(27, 2, 'FLOWER', 'Flower', '', '', 'Cannabis flower, also known as \"bud\" or \"nugs,\" refers to the dried buds of the female cannabis plant.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-jSOHQ6tZznOqmZsHTsmzqNSLNALaCxj04wr84bO3.jpg'),
(28, 2, 'Mix & Match - Low Shelf', 'Flower', '', '', 'Choose any combination of quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x2gJd8wb37NsU3c5HmrKYdvI0pFNkZvA5YmOQ9N0.jpg'),
(29, 2, 'Purple Punch', 'Flower', '', '', 'Larry OG x Grandaddy Purple', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-qH6E9gcIbEDT7Rem73QagHNlYNxYfI8og1uQI1AJ.jpg'),
(30, 2, 'Gelato', 'Flower', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-kA6eMsalac0OjtDHqttGVrBMTwlZb77Z6vNu8UvN.jpg'),
(31, 2, 'Jack Herer', 'Flower', '', '', 'Northern Lights x Shiva Skunk', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-nIHwbAvi0LCzlwgJzvEY9uhYvAEFsMjwyOdQCtTY.jpg'),
(32, 2, 'Mix & Match - Mid Shelf', 'Concentrates', '', '', 'Choose any combination of quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x2gJd8wb37NsU3c5HmrKYdvI0pFNkZvA5YmOQ9N0.jpg'),
(33, 2, 'Birthday Cake', 'Flower', '', '', 'Girl Scout Cookies x Cherry Pie', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-OIeIB6O50HyWYKbnpWO8Sp0ywsnCuFFV70z8K6vF.jpg'),
(34, 2, 'White Runtz', 'Flower', '', '', 'Runtz phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x1JS8oJcBIJFExr4RRGXyM7iRJ7LDi1Sn7g1HOkC.jpg'),
(35, 2, 'Lemon Buffalo', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-eG5N1RTKnKLqFHS0ugyuDL7DLk2ye8oGpVmOiF8m.jpg'),
(36, 2, 'Mix & Match - High Shelf', 'Flower', '', '', 'Choose any combination of quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x2gJd8wb37NsU3c5HmrKYdvI0pFNkZvA5YmOQ9N0.jpg'),
(37, 2, 'Dolato', 'Flower', '', '', 'Dosidos x Gelato', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-VomAw106pzun5RxgQj4gMZm9a6Hj5fIpAIJUlZ2P.jpg'),
(38, 2, 'Peanut Butter Breath', 'Flower', '', '', 'Dosidos x Mendo Breath', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-RORBKqEwbMe5XOiv8V5Y2HU49wPtHGuvTrL1qWAC.jpg'),
(39, 2, 'Tangie Cookies', 'Flower', '', '', 'Tangie x Gurl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-aYxYjiJ1gFxZIY0eT5tY8h9NNtYd8dsh5wjmRgrT.jpg'),
(40, 2, 'Mix & Match - Super Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x2gJd8wb37NsU3c5HmrKYdvI0pFNkZvA5YmOQ9N0.jpg'),
(41, 2, 'Super Glue', 'Flower', '', '', 'Skunk #1 x Northern Lights', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-i5Zwt2jjrJ1KReQLRRXG2l4m6QrkukTC1xvlzLiM.jpg'),
(42, 2, 'Cosmic Treehouse - Bacio Gelato - 27%', 'Flower', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-uscKOFHFOt9WwSBVscNaJWzh6e48ixatz7RvhAgz.webp'),
(43, 2, 'Crescendo', 'Flower', '', '', 'I-95 x Chemdawg x Mandarin Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x1JS8oJcBIJFExr4RRGXyM7iRJ7LDi1Sn7g1HOkC.jpg'),
(44, 2, 'Mix & Match - Bronze Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-kKi8AXUGqHdNI1Spt1TxKKCQVxJGik4BOhBucWKJ.jpeg'),
(45, 2, 'Cosmic Treehouse - Oreoz - 24%', 'Flower', '', '', 'Cookies & Cream x Secret Weapon', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-4efy6N3FTFsOyUks8hJJ9f96QAhM23ilxaV3kcpv.jpg'),
(46, 2, 'White Widow', 'Flower', '', '', 'Brazillian x South Indian', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-ea1TxE4lOjQxepD5FmtRpMzjS7z80owAOhsJeWa2.jpg'),
(47, 2, 'Bloom - Chocolope - 22%', 'Flower', '', '', 'Chocolate Thai x Cannalope Haze', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-ZGrLaEmyLIJL0tNLYrS9yn5br45qdUCXnjDK8IlY.jpg'),
(48, 2, 'Mix & Match - Silver Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-kKi8AXUGqHdNI1Spt1TxKKCQVxJGik4BOhBucWKJ.jpeg'),
(49, 2, 'Hit It - OG Kush - 30.81%', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-5p1W4hFbpFfkhbt2eRCn5NLY8pBNAhSU7NWVxvxR.jpg'),
(50, 2, 'Hit It - Pink Runtz - 30.05%', 'Flower', '', '', 'Runtz phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-0WnCrmCaiu3iQvDEaET1lGhcA3IuWVAKuAIEROv2.jpg'),
(51, 2, 'West Coast Cure - Laughing Gas - 27.5%', 'Flower', '', '', 'Sour Diesel x Cherry Pie', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-USUgESIq3JbGe0HxDezrdZ1tFgjvDjTcqoP5Bo5D.jpg'),
(52, 2, 'Mix & Match - Gold Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, and halves', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-kKi8AXUGqHdNI1Spt1TxKKCQVxJGik4BOhBucWKJ.jpeg'),
(53, 2, 'Hit It - Blue Dream - 30.29%', 'Flower', '', '', 'Blueberry x Haze', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-5xzSxg6h2KVZe6n7IIVxF7vVXnil6k0GjnB4lwVF.jpg'),
(54, 2, 'Rolly - Gorilla Glue - 30%', 'Flower', '', '', 'Chocolate Diesel x Sour Dubb x Chem\'s Sister', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-KhDaofhagXzICIBySP37GRxyrxovlfGJJPb7yC9Q.jpg'),
(55, 2, 'Rolly - Lemon Cherry Gelato - 34.5%', 'Flower', '', '', 'Gelato phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-UNFB0S2y9Td7fJQ9q2SDBOX8tjJ3rCxQo1LfzXHJ.jpg'),
(56, 2, 'Hit It - UFO Runtz - 33%', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-47lXZwIYTpRaT7rbwdejOEJ1KobOk1MHE8pPuf3p.jpg'),
(57, 2, 'Mix & Match - Platinum Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, halves, and ounces', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-kKi8AXUGqHdNI1Spt1TxKKCQVxJGik4BOhBucWKJ.jpeg'),
(58, 2, 'Hit It - CrystalCandy - 35.71%', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-K7RQqfoSyTdWiM2tQa9aO8kib3U0t8KrRx4YD2H6.jpg'),
(59, 2, 'SHAKE', 'Flower', '', '', 'Marijuana shake refers to the loose, fragmented pieces of cannabis flower that accumulate at the bottom of a bag or container. It consists of small buds, broken leaves, and trichomes that naturally separate during transportation or handling.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-prdTPr4SH50PuuRKaZQwLn90TE2v7tvlnIRfYWg7.png'),
(60, 2, 'Shake - Ice Cream Cake', 'Flower', '', '', 'Larry Bird x Wedding Cake', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/photos/Leafedin_GKlni1Q7WtvvRAYkZXgPYmQ5lSYAHAfVwhUXCpSv.jpeg'),
(61, 2, 'Shake - Girl Scout Cookies', 'Flower', '', '', 'Durban Poison x OG Kush', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-d0v0gAmSRDXmtnnkrXmflpUfp9QiiQfDREaGGvbx.jpg'),
(62, 2, 'Hit It Shake - Lemon Cherry Gelato - 37.09%', 'Flower', '', '', 'Gelato phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/photos/Leafedin_GKlni1Q7WtvvRAYkZXgPYmQ5lSYAHAfVwhUXCpSv.jpeg'),
(63, 2, 'Shake - Lemon Cherry Gelato', 'Flower', '', '', 'Gelato phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-FRiYtHyav5Ga0ocliHdOvT1zm9wasKYxq9ApIjqP.jpg'),
(64, 2, 'Mixed Shake', 'Flower', '', '', 'Mix of strains', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-qJ4WoXPBpTGvk9EZ7iwORPIiZbyPxXKcO9kkGLia.jpg'),
(65, 2, 'Shake - Inner Chi', 'Flower', '', '', 'Larry OG x OG Kush', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/photos/Leafedin_GKlni1Q7WtvvRAYkZXgPYmQ5lSYAHAfVwhUXCpSv.jpeg'),
(66, 2, 'Shake - Mimosa', 'Flower', '', '', 'Purple Punch x Clementine', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/photos/Leafedin_GKlni1Q7WtvvRAYkZXgPYmQ5lSYAHAfVwhUXCpSv.jpeg'),
(67, 2, 'PRE-ROLLS', 'Preroll', '', '', 'A pre-rolled joint, often simply referred to as a pre-roll, is a ready-to-smoke cannabis joint. The dispensary pre-roll is meticulously crafted by professionals, filled with ground cannabis flower and neatly sealed within a paper wrap.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-mEgwQqXIWvwIZuRMtUvOydsW6YVfZ9qYgcJGhJav.jpg'),
(68, 2, 'Jayne Hash Rosin & Flower Pre-rolls', 'Preroll', '', '', 'Assorted hybrid pre-rolls', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-dVwKR1XU9Kq0JakAGDCSEGWPameVeNZ5GIoQp8Z8.jpg'),
(69, 2, 'Baby Jeeters - Mai Tai - 43.97%', 'Preroll', '', '', 'Maui Waui x Tutti Frutti', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-gWte4IZiMroEKKfZC7WoQNXJx0EEbujEVCzB3wmO.jpg'),
(70, 2, 'CONCENTRATES', 'Concentrates', '', '', 'Concentrated THC Products (also known as hash oil, dabs, wax, earwax, honey, honey oil, resin, or shatter) is a product created by extracting THC from the marijuana plant.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-fIxTf5IPjr5sAsRpR1BHfBTHFScUP78KHjxyrrG9.jpg'),
(71, 2, 'Most High Budder - Lemon Squeeze', 'Concentrates', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-SbSRacu1vx4z2uTYpMltGD57WIHsByX2ijBbFVsO.jpg'),
(72, 2, 'Crumble - Lemon OG', 'Concentrates', '', '', 'Las Vegas Lemon Skunk x OG #18', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-M2FlRxJf5yT4nAYxPnvUOw6lul1PwykUWQ68R26N.jpg'),
(73, 2, 'Jayne Hash', 'Concentrates', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-yhswoPmzZW9NVkq3JBuKkD34nZDZS8SaOV7H2ENU.jpg'),
(74, 2, 'Most High Sugar - Jupiter OG', 'Concentrates', '', '', 'OG Kush phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-L4OxYEkUqO1f8ufsxSpLJeQ3GZJOzv8oDweD5Asc.jpg'),
(75, 2, 'VAPE CARTRIDGES & PODS', 'Concentrates', '', '', 'Simply, a cart is a glass tube that holds cannabis oil and contains an atomizer that heats and vaporizes the oil when attached to a battery. Carts often come filled with various types of oils, such as extracted THC oil or distillates.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-TeExH75YxSBKN7MQW6z1L881aHuaWcNHftBFF2w5.jpg'),
(76, 2, 'Gold Coast Clear Cart - Grape Ape', 'Vaporizers', '', '', 'Mendocino Purps x Skunk x Afghani', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(77, 2, 'Gold Coast Clear Cart - Ice Cream Cake', 'Vaporizers', '', '', 'Wedding Cake x Gelato 33', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(78, 2, 'Gold Coast Clear Cart - LA Confidential', 'Vaporizers', '', '', 'Afghani x California Indica', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(79, 2, 'Gold Coast Clear Cart - Northern Lights', 'Vaporizers', '', '', 'Afghani x Thai', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(80, 2, 'Gold Coast Clear Cart - Runtz OG', 'Vaporizers', '', '', 'Zkittlez x Gelato', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(81, 2, 'Gold Coast Clear Cart - Watermelon Kush', 'Vaporizers', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(82, 2, 'Gold Coast Clear Cart - Candy Kush', 'Vaporizers', '', '', 'OG Kush x Blue Dream', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(83, 2, 'Gold Coast Clear Cart - Cereal Milk', 'Vaporizers', '', '', 'Y Life x Snowman', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(84, 2, 'Gold Coast Clear Cart - Dirty Sprite', 'Vaporizers', '', '', 'Cinderella 99 x Arcata Lemon Wreck', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(85, 2, 'Gold Coast Clear Cart - Face Melt OG', 'Vaporizers', '', '', 'Grimace OG x Doc\'s OG', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(86, 2, 'Gold Coast Clear Cart - Italian Ice', 'Vaporizers', '', '', 'Gelato 45 x Forbidden Fruit', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(87, 2, 'Gold Coast Clear Cart - Lemon Heads', 'Vaporizers', '', '', 'Kush phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(88, 2, 'Gold Coast Clear Cart - Pina Colada', 'Vaporizers', '', '', 'Banana Kush x Starburst Bubba', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOutvfDyQhwWkV3Rdp9LWQXa1oBCXmR7wju2itin5NAy.jpg'),
(89, 2, 'West Coast Cure Cart - Juicy Papaya - 83.7%', 'Vaporizers', '', '', 'Papaya x Mango', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-5OsldXDnDd3mfrI2b4xlxgtr3ha5YUk0lPN6zCbD.jpg'),
(90, 2, 'West Coast Cure Carts - Lucky Charmz - 87.2%', 'Vaporizers', '', '', 'The White x Appalachia', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-LfFBvRXdCK8vvGof2InykGAbcWPYhP60I1NiNwWk.jpg'),
(91, 2, 'West Coast Cure Cart - Mango Haze - 89%', 'Vaporizers', '', '', 'Northern Lights #5 x Skunk x Haze', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-lv3q2YAPdxoSs6FuhLayPxDDTSp2nLUezJ3ZRwbs.jpg'),
(92, 2, 'Everdrop Cart - Gelato - 90.52%', 'Vaporizers', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-0mdKqMBSGBGoa6FvUV1z6voWw94aDKJOlL0J8Vtz.jpg'),
(93, 2, 'Everdrop Cart - GDP - 92.23%', 'Vaporizers', '', '', 'Purple Urkle x Bug Bud', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-fyh4zeKiYOG3dHe7gEradBtyJbcDW4slvYKwXCGB.jpg'),
(94, 2, 'Everdrop Cart - Jack Herer - 90.94%', 'Vaporizers', '', '', 'Northern Lights x Shiva Skunk', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-TeI9wsu1FYuMF3kxJ7jtmPG7GbwQCJXaIxbxslmC.jpg'),
(95, 2, 'Jeeter Juice Cart - Bubba Gum - 85.65%', 'Vaporizers', '', '', 'Bubba Kush x Bubble Gum', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-x1OfQ4s7u7bqtlOwWkYKmzhFNDO9x8u7kn5S7TC3.jpg'),
(96, 2, 'Jeeter Juice Cart - Grandaddy Purple - 91.75%', 'Vaporizers', '', '', 'Big Bud x Purple Urkle', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-20zE9nJRhSk4GQMn7I3QfwloK8hoN35KX3J1eMvM.jpg'),
(97, 2, 'DISPOSABLE VAPES', 'Vaporizers', '', '', 'Disposable vape pens are single-use devices that are filled with e-liquid, oil, or distillate. These types of vape pens are increasing in popularity due to their simplicity and portability. The battery is built-in and often rechargeable.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-2ctPBeCeQBPRpgW1C1nclMvvOarurhE2e5L7SOIg.jpg'),
(98, 2, 'Napalm Disposable - Animal Mintz - 87.73%', 'Vaporizers', '', '', 'Fire OG x Animal Cookies x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-lBITyAXJ7NHY4h2wSL9JXrOI270HGlXcE0pdJlEj.jpg'),
(99, 2, 'Napalm Disposable - Gelatti - 90.46%', 'Vaporizers', '', '', 'Gelato x Biscotti', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-pzQvtdECi6V6ob0NSECWxbVT3lUjdJSSrGhchXRV.jpg'),
(100, 2, 'Cannabeast Disposable - Strawnana - 80.5%', 'Vaporizers', '', '', 'Banana Kush x Strawberry Bubblegum', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-vZfyly2yPbUC1fW3qyaNC53vhp6BeTmiji1vNq2U.jpg'),
(101, 2, 'Cannabeast Disposable - Gelato - 85%', 'Vaporizers', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-JZBgKK4QvPXObN6yQrGpCrmw5PaEd7poSqnt11he.jpg'),
(102, 2, 'Cannabeast Disposable - Mojito - 83.6%', 'Vaporizers', '', '', 'Limegerian x Orange Blossom Trail', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-cqEw7gBWFDjhxVBhleRghuuaSiAjwFElp4C0Ar8A.jpg'),
(103, 2, 'Kushy Punch Disposable - Blue Raspberry - 87%', 'Vaporizers', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-PpKUTf3aseLWmuueEgVwdqaS4NFBIZ2hP7jUu92a.jpg'),
(104, 2, 'Kushy Punch Disposable - StrawnanaSmoothie - 88.5%', 'Vaporizers', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-zj7QQ4AKzkchUH57MqtBZ85yATdJ8gWYvVRuKo1S.jpg'),
(105, 2, 'EDIBLES', 'Edible', '', '', 'Edible cannabis products (edibles for short) are products containing cannabinoids that you eat or drink. Cannabinoids are chemical compounds found in cannabis that can affect your mind and body when consumed.', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-RF5XiVepzL82I1jeA26W5fK0BRYUjoZSFE2d2Cw6.jpg'),
(106, 2, 'Delights Gummies - Cherry', 'Edible', '', '', 'Cherry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-WnZAL51DIDynpE355YZ6MCZiE8AldOIe64kWvTrG.jpg'),
(107, 2, 'Delights Gummies - Blue Raspberry', 'Edible', '', '', 'Blue raspberry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-4FNHqBJ6Xp69lYI09bY8Z5xm9nsdt5DahIta8zb2.jpg'),
(108, 2, 'Delights Gummies - Peach', 'Edible', '', '', 'Peach gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-Yiknuz9RQsEj0y5lV7FX0CxjPCHuENFXdX83SH8d.jpg'),
(109, 2, 'Delights Gummies - Strawberry', 'Edible', '', '', 'Strawberry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-VcFYuweFKOKPFIj6L8YCptVi0OZkQbnKKmwjLgch.jpg'),
(110, 2, 'Highatus Gummies - Pomberry', 'Edible', '', '', 'Pomberry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-HmfUnqeuUI1NiVos8AKi58EyruYazN0cDaZc1nkU.jpg'),
(111, 2, 'Highatus Gummies - Watermelon', 'Edible', '', '', 'Watermelon gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOutOph4OPyXrehPR8YO5jnm8VFnK3jNBpnC2EZEOTA0.v1642056119.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-W10aqI3VhgMRJLX2JEr4cXyaiRvylnxiIQV78RYj.jpg'),
(112, 3, 'White Runtz', 'Flower', '', '', 'Runtz phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-urXBmpkNDzBg2ezrw8jDfuSAiLGwE8xxfgk6PDen.jpeg'),
(113, 3, 'Jack Herer', 'Flower', '', '', 'Northern Lights x Shiva Skunk', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-dUPmiN0pXrwoedEGI3oH1jjTalemsy8B6tSE8b8K.jpeg'),
(114, 3, 'Birthday Cake', 'Flower', '', '', 'Girl Scout Cookies x Cherry Pie', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-NbC6VlWOQTqkLLAagC0CElkFL9BD1T6YEK5fNZoi.jpeg'),
(115, 3, 'Lemon Buffalo', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-t2CqhOlUSkCX3HjqFakFjXwjPBYDuvplbXcgLX9F.jpeg'),
(116, 3, 'Super Glue', 'Flower', '', '', 'Skunk #1 x Northern Lights', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-AEeDnISlTY4GMc61ZxaHNoO6oyCA3rnBdZ1lG0xU.jpg'),
(117, 3, 'Crescendo', 'Flower', '', '', 'I-95 x Chemdawg x Mandarin Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-xtdtSxlGUbF318JnkCYUJmfFA0F1q45y12loFXKC.jpg'),
(118, 3, 'Mix & Match - Bronze Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, and halves AKA mix & match', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-M3hPnm9tvsr5AnX9EiHPnvpfVRNhNb8Cf7W4BZSx.jpeg'),
(119, 3, 'Cosmic Treehouse - Oreoz - 24%', 'Flower', '', '', 'Cookies & Cream x Secret Weapon', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-wIWxoIrzfOMMK0na8qBSuVUUCKWyb4oMEKmuXQI9.jpg'),
(120, 3, 'Cosmic Treehouse - Bacio Gelato - 27%', 'Flower', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-TTVdBPDhAwTIYCJr5u3v9WB1ZlvhxxiONh83HeXY.jpg'),
(121, 3, 'Bloom - Chocolope - 22%', 'Flower', '', '', 'Chocolate Thai x Cannalope Haze', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-Vuov7XJ0o1rmsuCbLh5kIWhO5AoKWApAM6IcImL9.jpg'),
(122, 3, 'Mix & Match - Silver Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, and halves AKA mix & match', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-M3hPnm9tvsr5AnX9EiHPnvpfVRNhNb8Cf7W4BZSx.jpeg'),
(123, 3, 'Hit It - OG Kush - 30.81%', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-451k1voevpuZUoGnq5WvpeLUtrwdzPzu9pMvm6hx.jpeg'),
(124, 3, 'Hit It - Pink Runtz - 30.05%', 'Flower', '', '', 'Runtz phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-RmsSraxRJBXYgkRFEuTmHFkD3EKJpQqAEOnsj1UF.jpeg'),
(125, 3, 'West Coast Cure - Laughing Gas - 27.5%', 'Flower', '', '', 'Laughing Buddha x Gas', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-SuGnwYIZR0IT9FWkMH1flgsbFfEk5gGVKB8MQc5d.jpeg'),
(126, 3, 'Mix & Match - Gold Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, and halves AKA mix & match', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-M3hPnm9tvsr5AnX9EiHPnvpfVRNhNb8Cf7W4BZSx.jpeg'),
(127, 3, 'Hit It - Blue Dream - 30.29%', 'Flower', '', '', 'Blueberry x Haze', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-jBBaW90RE6qpR3HZ7oCcrgtnGBm6eWcxgKP5npfA.jpeg'),
(128, 3, 'Rolly - Gorilla Glue - 30%', 'Flower', '', '', 'Chocolate Diesel x Sour Dubb x Chem\'s Sister', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-2CNscLXWhcb35QNaE0tPdmt1FIYBnhKoEYukFd0K.jpeg'),
(129, 3, 'Rolly - Lemon Cherry Gelato - 34.5%', 'Flower', '', '', 'Gelato phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-RfHClffSe5H0LSmcgrUL2DtzLxzvAHOQJkOKkU2h.jpeg'),
(130, 3, 'Hit It - UFO Runtz - 33%', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-XaAdeIhAqyUh5R6n9G8WRPXJo5ZrZc28affAo5wb.jpeg'),
(131, 3, 'Build Your Own - Platinum Shelf', 'Flower', '', '', 'Choose any combination of 8ths, quarters, and halves AKA mix & match', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-M3hPnm9tvsr5AnX9EiHPnvpfVRNhNb8Cf7W4BZSx.jpeg'),
(132, 3, 'Hit It - CrystalCandy - 35.71%', 'Flower', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-hwG7re5e4VNyVZjhtclSFxwTbaDn4hRCCedOwSR7.jpeg'),
(133, 3, 'Shake - Ice Cream Cake', 'Flower', '', '', 'Larry Bird x Wedding Cake', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-fdRHwdK5fNza1Up5GJPo99hUOc3TxuI6L1n2gfjp.jpeg'),
(134, 3, 'Hit It Shake - Lemon Cherry Gelato - 37.09%', 'Flower', '', '', 'Gelato phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-fdRHwdK5fNza1Up5GJPo99hUOc3TxuI6L1n2gfjp.jpeg'),
(135, 3, 'Shake - Lemon Cherry Gelato', 'Flower', '', '', 'Gelato phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-Sxn9tVGfKJ6GhRS30xjyNYw5s056zgRJ5tkzKIFE.webp'),
(136, 3, 'Shake - Inner Chi', 'Flower', '', '', 'Larry OG x OG Kush', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-fdRHwdK5fNza1Up5GJPo99hUOc3TxuI6L1n2gfjp.jpeg'),
(137, 3, 'Shake - Mimosa', 'Flower', '', '', 'Purple Punch x Clementine', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-fdRHwdK5fNza1Up5GJPo99hUOc3TxuI6L1n2gfjp.jpeg'),
(138, 3, 'Jayne Hash Rosin & Flower Pre-rolls', 'Preroll', '', '', 'Assorted hybrid pre-rolls', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-gx67dhAXm4Xwx3W2bdPWfEw71WCjCFhFD9vW1uzA.jpeg'),
(139, 3, 'Most High Budder - Lemon Squeeze', 'Concentrates', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-FTG02Nx8wrEZ7VxUiVpVA0u8j4lEJUF5wzUGSKPp.jpg'),
(140, 3, 'Crumble - Lemon OG', 'Concentrates', '', '', 'Las Vegas Lemon Skunk x OG #18', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-y4VMMk9JQr0OhseVkigSr3MNiMS3nl2LIDZ5ZayF.jpeg'),
(141, 3, 'Jayne Hash', 'Concentrates', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-NXXdZtzI6JD7nAmuZABusdJ6z9YDxcQtlFkAYAbw.jpeg'),
(142, 3, 'Most High Sugar - Jupiter OG', 'Concentrates', '', '', 'OG Kush phenotype', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sOo0waDdF8uXdbjeuGGduQeWHwo1BW3Zhv6GnZsx.jpg'),
(143, 3, 'Gold Coast Clear Cart - Grape Ape', 'Vaporizers', '', '', 'Mendocino Purps x Skunk x Afghani', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(144, 3, 'Gold Coast Clear Cart - Ice Cream Cake', 'Vaporizers', '', '', 'Wedding Cake x Gelato 33', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(145, 3, 'Gold Coast Clear Cart - LA Confidential', 'Vaporizers', '', '', 'Afghani x California Indica', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(146, 3, 'Gold Coast Clear Cart - Watermelon Kush', 'Vaporizers', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(147, 3, 'Gold Coast Clear Cart - Candy Kush', 'Vaporizers', '', '', 'OG Kush x Blue Dream', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(148, 3, 'Gold Coast Clear Cart - Dirty Sprite', 'Vaporizers', '', '', 'Cinderella 99 x Arcata Lemon Wreck', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(149, 3, 'Gold Coast Clear Cart - Face Melt OG', 'Vaporizers', '', '', 'Grimace OG x Doc\'s OG', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sT43YfHv6KHsUyE7JKMcvUlHOwtnhT95eLG7wJ1o.jpeg'),
(150, 3, 'West Coast Cure Cart - Juicy Papaya - 83.7%', 'Vaporizers', '', '', 'Papaya x Mango', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-2EXyAGxm1oDrF0bBZNphV2THMYEHiT8ksXfekqV0.jpeg'),
(151, 3, 'West Coast Cure Carts - Lucky Charmz - 87.2%', 'Vaporizers', '', '', 'The White x Appalachia', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-sXjLhW9GmYAqHEAuiHMzsOEW82SKkLq0LsMoCSDC.jpg'),
(152, 3, 'West Coast Cure Cart - Mango Haze - 89%', 'Vaporizers', '', '', 'Northern Lights #5 x Skunk x Haze', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-JaD9i3AAIfC45Wn06QhvSXe9OiF0Qow3w1IELRwu.jpg'),
(153, 3, 'Everdrop Cart - Gelato - 90.52%', 'Vaporizers', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-1sfNNh5SQXCZGh2hhFTsqoYYRuFFKIjqcaa7Ekbe.jpeg');
INSERT INTO `menus` (`id`, `vendor_id`, `name`, `category`, `flavors`, `effects`, `description`, `imageUrl`) VALUES
(154, 3, 'Everdrop Cart - GDP - 92.23%', 'Vaporizers', '', '', 'Purple Urkle x Bug Bud', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-3uOf2YKXByk2XV10Kub3HEmlyApO0hRPVYrsDeZF.jpeg'),
(155, 3, 'Everdrop Cart - Jack Herer - 90.94%', 'Vaporizers', '', '', 'Northern Lights x Shiva Skunk', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-TAIuoakSh9LsmZruecTNDh3N3HZRrQpEyn6aBqRa.jpeg'),
(156, 3, 'Jeeter Juice Cart - Bubba Gum - 85.65%', 'Vaporizers', '', '', 'Bubba Kush x Bubble Gum', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-t0mkwP2lb5dgxwjlyH4TnFaLLRTlUSBwdh0t5eiI.jpg'),
(157, 3, 'Jeeter Juice Cart - Grandaddy Purple - 91.75%', 'Vaporizers', '', '', 'Big Bud x Purple Urkle', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-BLhauZMoJpGwUgkJTdGJqFktcEuY4pr4E2jFLh7H.jpg'),
(158, 3, 'Cannabeast Disposable - Strawnana - 80.5%', 'Vaporizers', '', '', 'Banana Kush x Strawberry Bubblegum', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-3dgncZiv2Djp1ZkSnoQP75HTfnBPrtT3pgVjNNSu.jpg'),
(159, 3, 'Cannabeast Disposable - Gelato - 85%', 'Vaporizers', '', '', 'Sunset Sherbert x Girl Scout Cookies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-tRt2Hg3faSmoYoyAkaNDkNX3464FS7rQcnrA8ciW.jpg'),
(160, 3, 'Cannabeast Disposable - Mojito - 83.6%', 'Vaporizers', '', '', 'Limegerian x Orange Blossom Trail', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-b9loZd9x2Qs7fz1Ct9lj1mZfI9SjJxh8LBv5i8C5.jpg'),
(161, 3, 'Kushy Punch Disposable - Blue Raspberry - 78.8%', 'Vaporizers', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-43hKBKaEhNtMSD3bOGnMtTUE4k5xo4czaIuDmS8I.jpg'),
(162, 3, 'Kushy Punch Disposable - StrawnanaSmoothie - 88.5%', 'Vaporizers', '', '', 'Unknown genetics', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-7H9xJO0e2OleAOpoT43cMK6uoL5c7NUg2N3hZoEs.jpeg'),
(163, 3, 'Delights Gummies - Cherry', 'Edible', '', '', 'Cherry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-aJNpcRpg0JpkqYT0D3UHJYhwaVMkSResGbRLhlQp.jpeg'),
(164, 3, 'Delights Gummies - Blue Raspberry', 'Edible', '', '', 'Blue raspberry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-A9yQqVs5XqptOQCPGwc4fk5Owb28lJSZ2hiUtHRC.jpeg'),
(165, 3, 'Delights Gummies - Strawberry', 'Edible', '', '', 'Strawberry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-H3tCDUebiyRADixyut66DNMVTmo4CHd5TBgJw6B9.jpeg'),
(166, 3, 'Highatus Gummies - Pomberry', 'Edible', '', '', 'Pomberry gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-1SBKiADeiY0RAyVHkwU6OJuSOlV8J7KK2oSAy36U.jpeg'),
(167, 3, 'Highatus Gummies - Watermelon', 'Edible', '', '', 'Watermelon gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-ZqQ4TxjVbuYXsgqbVdIX8mrnwoM8xZAMXPgYepti.jpeg'),
(168, 3, 'Highatus Gummies - Green Apple', 'Edible', '', '', 'Green apple gummies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-wrYylpyUbFON0mPVL8KjsR7fGCFTu49AKOffcWA4.v1704159320.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-xihzLMJjFbVCHq2rBqdbQVDoTQxaq5vU8HO69V0y.jpg'),
(169, 4, '🫚🍞🍪GingerBread Cookies🍪🍞🫚', 'Flower', '', '', 'Run run run as fast as you can, he’s high right now so you CAN catch the gingerbread man.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-hC3saO2xZ0A94vPzfTcxfd6EqSrbHYTw4WmlEXte.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-hC3saO2xZ0A94vPzfTcxfd6EqSrbHYTw4WmlEXte.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-QG20FKxk0Up1kqYRTklRSzimQYzEuKz7MYiLpazm.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-efeGfYQhEPostsfIlk6V8ElBg9SdpyhdK5B1ZOBV.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-Mr35pJ58egHqZ3c7FauE8PbB4WBQQqBw9kI3LabM.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(170, 4, '🍪🍦Cookie Sundae🍦🍪', 'Flower', '', '', 'Balanced hybrid. Creamy cookie Terps, with a hint of fruity. Can’t go wrong here, another Green Midas Selection you don’t wana miss.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-aOXdBMLaWJNeiQjdAvO7p78TJZXjUgr9QZnD54uU.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-aOXdBMLaWJNeiQjdAvO7p78TJZXjUgr9QZnD54uU.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-de2LB6M4wCeWA4mvot4QVKXNLqtQHDcy7tMkkt15.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-OSaBaliRvTLwevugHDDf0EgAHNegng7zHHkK1gDF.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-FShuH5ZfF4MWJP5SBKgWTjBhb2uLELABVtKJmBPW.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(171, 4, '🪂SKY🪂 (2indicas)', 'Flower', '', '', 'The new kid on the block. SKY is a top notch new brand, that uses the same growers as Marshies, and Yummies, in fact all 3 of these brands use the growers from BombPopz. These 2 cereal bar strains are bussin 👌🏽🤤😋', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-Ewl4FSLsJFuccOfV9ItQ6yxx11SyRPPTh0xbRA1Z.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-Ewl4FSLsJFuccOfV9ItQ6yxx11SyRPPTh0xbRA1Z.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-CDwiaqiOspfejR0XeXBduXtoJPXuIXPf3CO7rshH.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-KaYo8wJlT4TpbjLVmNeMk53mfoqOlGNRLQGpFcnK.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(172, 4, '⚪️🤤MARSHIES🤤⚪️ (2indicas/1hybrid)', 'Flower', '', '', 'Marshies never falls short 💪🏽 A super tasty lineup, some of the tastiest smoke you’ll find on earth 🌎. Prove me wrong', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-jOtTPggJtThAJI2XIQPgl5EBRFKoVbm3bQhkZC2V.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-jOtTPggJtThAJI2XIQPgl5EBRFKoVbm3bQhkZC2V.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-oPGAO4PWzi0S8jJs1rvFGD1ZOr858k6K6TlCr41Q.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-Wq5qyOzF3tgi6tDrX3AGMB37KfPyl684RrFhKKeR.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(173, 4, '😋🤤YUMMIES🤤😋 (1hybrid/1indica)', 'Flower', '', '', 'Yummies back with a couple tasty treats for that ass! Get your movie snacks ready, kick back with some Netflix after work, with the perfect cinematic 🎥🍿🥤smoke', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-y9A63Hb1dU4HmkA6ruRvxxY6oijgz6A8twmgZNKl.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-y9A63Hb1dU4HmkA6ruRvxxY6oijgz6A8twmgZNKl.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-fXXhrWHtEMOOHxOpWPUa1FS7OY6cjwYoZkv1qYHh.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-Cqh1vye1pI1q438KGWPVBVRUcflvKyAPcIwO0qN5.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(174, 4, '🗽TORCH🗽 Dispos 2Gram Diamond Live Resin', 'Vaporizers', '', '', 'Check pictures for exact flavors available. No pen required, already built in, comes ready to use. Nice variety of sativas, and hybrids.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-1GzqY4Jfqo0JcyWgw10ViwmaDBG1a48z552sCydx.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-1GzqY4Jfqo0JcyWgw10ViwmaDBG1a48z552sCydx.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-oql7smfioh8Ohx0ExQquts8jQQIrR1JuhStKuwI3.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-hulVrdKKJSkenvRc8HHuOqXLiBgbsUk0DobOA70o.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-VDTPQe9vWUrwEfaQJ9ZNZYalbMBVMUdtNa4XQwIe.jpeg'),
(175, 4, '🔵🦓Blue Fruit Ztripez🦓🔵', 'Flower', '', '', 'Indica dominant hybrid 70/30. This strain was originally bread by the BackPack Boyz. Sweet fruity bubblegum flavor with hints of 🍇 and 🫐. Great smoke 💨', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-8L8mlxYmXbKGJG5UsYVAYmyB7GSPiYYyHRa39IRw.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-8L8mlxYmXbKGJG5UsYVAYmyB7GSPiYYyHRa39IRw.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-HHkEHK5nRNk7ainCNrmXHOqx2bPcUH9zzJ5gOzFy.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-lxOXuRAoQrMwC0TP7ZVOptKVIlE9DYvKYwf5ffRV.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(176, 4, 'NEW Strains! WHOLE🫠MELTS🫠 LiveResinSugar 15/g', 'Concentrates', '', '', 'Gelato🍨Edition! WHOLE MELTS Live Resin Sugar. 16 strains available, check the second picture for exact strains available. Comes in original jar if you order an oz of one strain. Breakdowns will be in smaller plastic jars.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-4SrLxdoafmlBdK92gPEaCUQLxXUXw49MoIdh9zF2.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-4SrLxdoafmlBdK92gPEaCUQLxXUXw49MoIdh9zF2.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-3oFsFo4fGxGhKKdnDbmvmiVqg45I5agzTIc8RNvT.jpeg'),
(177, 4, '🦍🟢Gorilla Glue🟢🦍', 'Flower', '', '', 'A classic🎻 this indoor batch is SMOKIN💨VERY LOUD Authentic GG4 Taste, The Terps scream gluey super gas, the taste is fu(kin incredible 🤤😋 hands down loudest nug you’re gona find for the price on this website or anywhere else. Maryjanium Foreal.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-08ovU8TvML3nSJkgjKP3uU0fQEyKYSBJhmaLZqEQ.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-08ovU8TvML3nSJkgjKP3uU0fQEyKYSBJhmaLZqEQ.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-UxgkUUcz7zw4s1b6CA0CLM5HKyCXeQG4NVtezWea.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-NUj3vQZA63qMQaJOLTSVsJ2HWA7PsMTvsbLlpvT7.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-RzU7HnckHU3S9Bb6AnpNXHyp7e2BhaD3Ddw8sAfB.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(178, 4, '🎤🎩HIGH TOLERANCE🎩🎤 (1indica/1hybrid)', 'Flower', '', '', 'HIGH TOLERANCE back with a couple more tasty bangers. Both indicas. Thai Boba (indica) is self explanatory, White Rocket Pop (hybrid) tastes like a white Cherry Icee 🤤😋. Smoke as clean as it gets.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-GFqhPVTixfEd5OxT7NPLcXEKf6atccEyNAuKsban.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-GFqhPVTixfEd5OxT7NPLcXEKf6atccEyNAuKsban.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-jH9VEhCFJzWPidJ0Urs7q7S9WmkNiveatFa0ZBZG.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-tgB0cvShrR9ldVPO9aZMC6WVkKoRQcf7AdncgcSF.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-3tOAdqGd3g1FA0m5OUUkSkGvCEnJaF4c7vmpamCW.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(179, 4, '🍋🍒🎈Lemon Cherry Airheadz🎈🍒🍋', 'Flower', '', '', 'Easy peazy Lemon Squeezy, all over them cherry airheads please 🤤. She’s a beaut. Nice soft buds, great texture. Great smooth clean smoke.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-mPpzuv5qTEEIf2n6WxMeYzJSzmO6uV2w7YcEbNlD.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-mPpzuv5qTEEIf2n6WxMeYzJSzmO6uV2w7YcEbNlD.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-2Qx36NPo1aUwcsqafvB8ErSpjvyLhQ0LgkiKDXsG.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-9x1QbudFX3bdowpABdUHP0xMYF2EPuJdxKFQYVOL.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(180, 4, '💣💥BOMBPOPZ💥💣 (1indica, 1sativa, 1hybrid)', 'Flower', '', '', '💣💥BombPopz💥💣 back with another lineup exploding🤯with flavor‼️ CaptainCandy comes with a CaptainCandy Lighter, Blue SourStraws comes with SOURPOWER Candy, Nerdsz Popsicle comes packaged just like the BombPopz popsicle does 😋🤤', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-dIVeFHDXxiCVneTccyALzKnkCGRnAJ6KLomhUw6e.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dIVeFHDXxiCVneTccyALzKnkCGRnAJ6KLomhUw6e.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-NDiKUDUgnc9DGwPCp5xVzbTLGVDKTcaXacHhtH2X.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-JNBcBWB0eu9iFGkBroNH0g7qNnabXRvVd3KmtJ4O.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-HvxjefjVpT3HeKPiChjPsTIP2JSJiYMzoeVh5UU0.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-WBPsSa0sxXxSR9SQMFLZ99cH2U1qWaO63YFJDG06.jpeg'),
(181, 4, '🛩️⚪️Jett Puffs⚪️🛩️ By JettPacks', 'Flower', '', '', 'This is one to remember. Strong unique flavor, it tastes like marshmallows roasting on some hooka 😆 treat yourself to something special', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-a0EKUnaGv38TzJ8vpoyTDH4GegQw90kPPRGuJuzE.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-a0EKUnaGv38TzJ8vpoyTDH4GegQw90kPPRGuJuzE.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-7QZPhoRw6ESN3xymrlPtCMEPIWlh6KxEPB0LKHSG.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-iRld65e9A3mKuL3MLZt7y4hUlzJi9EOX0qEq63uH.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(182, 4, '🍨😈Gelato#33😈🍨', 'Flower', '', '', 'Balanced hybrid, 55%indica/45%sativa. Very tasty za, original Gelato flavor you can’t deny. Parent to many strains, Gelato#33 has a reputation for a reason 💪🏽', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-3EQRoeMbeupdvNSAAE8a2fG8QtsMUMstsTZYBg7u.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-3EQRoeMbeupdvNSAAE8a2fG8QtsMUMstsTZYBg7u.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-suPjyEhkZtVX1JL1OXH0FQboPQEqWaz3fIqVEy6x.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-XH2htUNvJUJxBzR8dhQR7ilrbcOZ8FyjoELDsX2j.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-VNKNy37MiOugxdeE5jd43tCQ85qVyl9CUarwBi3E.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(183, 4, '🧊🍨🥶IceLato🥶🍨🧊', 'Flower', '', '', 'Wedding Cake x Gelato 33. Fresh icy nugs. Great smoke for the price! Well blossomed buds not too stemmy, you won’t be disappointed. Heavy couch lock indica', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-dxpKZu3NY5WJjBdYsKhLhJxLiR7czT4xXebo3XEk.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dxpKZu3NY5WJjBdYsKhLhJxLiR7czT4xXebo3XEk.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-ITFt9RUc2gcPpKAOPB3OkJIZCstPnHokMNPHU41F.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-7zjltn7Zh3NttUhY812xoycB3csIkc6It0cXjGH1.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-KXj7wnsmTT4PJSMHZNY9Us7a4xJ27H47o9JOAO5r.png, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-dVWhDAmcDb655e98aFBAuMtxVaj8LIQ49Z7ike5S.jpeg'),
(184, 4, 'KAWS 🌒Moonrocks🌘 🫐Berry🍓Edition! (16 strains)', 'Concentrates', '', '', '16 dif strains to choose from. If you buy a whole oz you get it in the original jar. Check the picture for available strains.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-2eKUpNv0Ev1fS8wLuwBB80zD4WSRvFuWH0t5086D.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-2eKUpNv0Ev1fS8wLuwBB80zD4WSRvFuWH0t5086D.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-iIPqhhBjIkZONWQO06lzWn1KMATipriWSmaLny7p.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-QHWSp4NlE3b0mykVtWoA6YA1TDk9ORpH6ehCUKG2.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-OEVhBxGPg7UY0COs2bRYrRcsRWPmrYjZ1mPRd2BK.jpeg'),
(185, 4, '🫠MELT x PACKWOODS Dispos 2Gram Diamond Live Resin', 'Vaporizers', '', '', 'Check pictures for exact flavors available. No pen required, already built in, comes ready to use. Nice variety of indicas, sativas, and hybrids.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-DClSQfzA9mptNChjBgJcJDXbGtM9XqBLkkZZs1LF.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-DClSQfzA9mptNChjBgJcJDXbGtM9XqBLkkZZs1LF.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-6KVlyBOrB4175jrR3Bp5tm87YKUEEQxhKQPM6Vdy.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-MoLPeInmKwCYHUs0L8xoaoiLrOgLUCCbuk5nuGXt.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-TsHlliTMem4CzeZb89Ux8njooX21ulbgPo5PFKBP.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-ttv2FOCThuPsYnHC3mheOjWJ06WIGdq7kVlVNV2L.jpeg'),
(186, 4, '🧊🎁ICE BOX🎁🧊 ❄️Snowballs❄️ INSANE!', 'Concentrates', '', '', 'Comes in prepackaged 7g Jars. VERY DIFFERENT from ALL the snowballs I’ve had. More concentrate in between the snow and the bud, categorizes more as a concentrate to mix with flowers. Can be smoked on its own too, but ⚠️💪🏽 you don’t need much!', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-nQfceMxg4Z4TTeFp8fruYRITzAgrKFMU3Eh0dKV4.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-nQfceMxg4Z4TTeFp8fruYRITzAgrKFMU3Eh0dKV4.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-QRVJ3croAdfqdUja3CrBAQqgnFwv8km7SeAHTUj7.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-hmASDOdSfBgMA7nc2qCH9XL78JLtpZKOAVhgB3V6.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-GoE96w4VXXdCcQ40it4XFpWatzKh2i2fysv8ZGe8.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-0GcHVImD4jGTqWCDCUBYF4gMzUqpUyOpvwMbC9xE.jpeg'),
(187, 4, 'New round of 🛒BODEGA EDIBLES!🛒', 'Edible', '', '', 'The pictures show all the options. Mix ‘n’match for deals. 1 pack is 1 dose. These are very 🤤tasty😋. If you have low edible tolerance eat a half pack.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-l1SSgItRZh8M3qRKzYFMH5EnTR42rR6fljD653lU.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-l1SSgItRZh8M3qRKzYFMH5EnTR42rR6fljD653lU.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-WUE97OglivuA8hHkWli0IiaFhmA98HaNiVdy4lTr.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-K3gcQqbbpqrTGdpsq3sw18Tvfrf5i007REsg6uqa.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-PtQiAhXg0jOpoaLwu65X01RYVYUG6vkwcS5j39eM.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-z6zAqCHO7MTGz4BDA1zl8bED5jIVqk6NHjR8beZQ.jpeg'),
(188, 4, '🍋‍🟩LIME🍋‍🟩 Brand syrup edibles 1000mg', 'Edible', '', '', 'These are pretty tasty 🤤', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-qxOTUN0yzpbGRX9V6hwdCXiU4kzkAmGkDMSapvaU.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-qxOTUN0yzpbGRX9V6hwdCXiU4kzkAmGkDMSapvaU.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-DY1KcJoSGp2mkJfbiLjiU289WNQeUDNaSISEA4lo.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-hrnEFGFrTYR74GdbRkm3mzrRHLiVq4GAYb0NeqcB.jpeg'),
(189, 4, '🍰CAKE🍰 Carts', 'Vaporizers', '', '', 'Indicas, Sativas, and Hybrids. Available strains/flavors shown in the pictures. NEW FLAVORS IN THE LAST PICTURE', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-K6XVzff4yLKcd6tB7vxMEY3GkDi1kIxJsFlqdIMV.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-K6XVzff4yLKcd6tB7vxMEY3GkDi1kIxJsFlqdIMV.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-XlPlevOHSVJHY3074UP1FoKjcCd1Y9l99Xxkm6y1.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-T78YLZidDIFqkWdViHkCLG4n8kvc84vs26spCdxO.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-nL19wB1ANIwyHDQJgJr05YckN5HpVcm8qbX9hjNQ.jpeg'),
(190, 4, 'Live Resin Sugar by 📣LOUD📢 - 20/gram (5 strains)', 'Concentrates', '', '', 'Available strains shown in the pictures 👆🏽\nComes in original jar if you order an oz of one strain. Breakdowns will be in smaller plastic jars because they come in oz jars originally.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-vSgJyKJzIVuftMU48NmKe9KmBW9JA2nnx4r8AYd3.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-vSgJyKJzIVuftMU48NmKe9KmBW9JA2nnx4r8AYd3.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-sN5xjYOKghGkwd1X82XB2chqs5KX7AOgTPaTLaoq.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-WD5ZHQNtczDOgJGEatryQ2FELWVK4bvbJYb9GGhw.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-wnLbCaHqlj9ZH3YsOA01tJudGp2QkrAatxqSQvq9.jpeg'),
(191, 4, 'Hash Rosin! (Monkey🐵Berries🍓🫐) jarred by the gram', 'Concentrates', '', '', 'Super 💪🏽. For the true Dabbing connoisseur! \nMonkey Berries Hash Rosin by the gram jar.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-BFWgVEnZhTksjn5MmF4H4MKJFJySAIp31HuonFlJ.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-BFWgVEnZhTksjn5MmF4H4MKJFJySAIp31HuonFlJ.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-HCvh6vmX2Sd3uFZX8sEbthzbmlI271pB9yrGb451.jpeg'),
(192, 4, 'Hash Rosin! (🍮Carmelita🍮) jarred by the gram', 'Concentrates', '', '', 'Super 💪🏽. For the true Dabbing connoisseur! Carmelita Hash Rosin by the gram jar.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-RZziPsKqgvEiLJraVfcdLxxwoz3f8haISvggVvev.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-RZziPsKqgvEiLJraVfcdLxxwoz3f8haISvggVvev.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-YEfcagJ6UfNZfuipmWniGusRAKliaX38YV5y0xPR.jpeg'),
(193, 4, '🍫🍫🔮🔮🍫🍫', 'Others', '', '', 'Trippy Chocolate Bars, inquire for details and pics. Brand: Tidal wave . Check pics for more info', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-AI8TRra7OlyNAjPBjBT5DWD5hV5LNuT8XrmkDRM8.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-AI8TRra7OlyNAjPBjBT5DWD5hV5LNuT8XrmkDRM8.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-4K56hfdNXcZsaKe9UpKF8l7SRi1VgnvmmtkZfJex.jpeg, https://leafedout.com/storage/usercontent/thumbnails/LeafedOut-C3MorN6iH2Qw6S9YyZLCORf67vKa62WGxvFeWY1b.jpeg'),
(194, 4, '🔮🔮🔮🔮 Albinos', 'Others', '', '', 'Albino Gorilla, and Albino Jack Frost', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-HwzCxcrTUiB9USLKSrCwsS4zLHfZrKrXwwFSXpNi.png'),
(195, 4, '🔮🔮🔮🔮', 'Others', '', '', 'Makilla Gorilla, Squat Mak, Hillbillies', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-xitmYv2HMa6JEgjXaf6OYm6dNxoEuNPj1v6nNLfH.jpeg'),
(196, 4, '🏥Topical🧴 2 oz  THC/CBD 2000MG (PRE-ORDER)', 'Topicals', '', '', 'PAIN RELIEF skin cream product ease pain and reduce inflammation, SORENESS, ACHES, JOINT PAIN, ARTHRITIS YOU NAME IT..\nhas to be pre ordered or direct shipping, either way there will be shipping costs', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-DWyuRxeFRwGqNLC1D0clgnVdgTYHK71bYszudWx5.jpeg'),
(197, 4, '🔮DMT🔮 CARTS (PRE-ORDER)', 'Others', '', '', 'extracted from the natural Mimosa Hostilis root bark from the Brazilian Rain Forest. These full gram cartridges fit on a standard 510 thread battery twist pen.\nMust be pre ordered for direct shipping.', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-UZgnDPb2IBeKybIhzQyWfIME3Mut7VxSsL828Y94.v1675785351.jpeg, https://leafedout.com/storage/usercontent/photos/LeafedOut-arg6PJvtcygbR8aOGlOb0rKr1bTS9qIUmcerTCQO.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `vendors`
--

CREATE TABLE `vendors` (
  `id` int(11) NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `photo` varchar(500) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `rating` varchar(255) DEFAULT NULL,
  `numberOfReviews` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `joinedDate` varchar(255) DEFAULT NULL,
  `numberOfFollowing` varchar(255) DEFAULT NULL,
  `deliver` varchar(255) DEFAULT NULL,
  `minOrder` varchar(255) DEFAULT NULL,
  `products` varchar(255) DEFAULT NULL,
  `specials` varchar(255) DEFAULT NULL,
  `additionalComments` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `vendors`
--

INSERT INTO `vendors` (`id`, `url`, `photo`, `name`, `username`, `rating`, `numberOfReviews`, `location`, `joinedDate`, `numberOfFollowing`, `deliver`, `minOrder`, `products`, `specials`, `additionalComments`) VALUES
(1, 'https://leafedout.com/cannabis-vendor/greeninflorida', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-v1oBhMG4r9X3zIHKuLIpDryQVFSL1cirHAJIeSJ6.v1671672026.png', 'GreenInFlorida', 'greeninflorida', '5.055555', '52', 'Bradenton, Florida', 'Dec 2022', '68', 'Tampa to Venice. Bradenton, Sarasota, St. Pete, Sun City, Brandon.', 'No minimum pickup or meetup, delivery depends on order and distance.', 'Flower, Cartridges, Pre-Rolls, Concentrates, Edibles', '50 to 240 Os', 'Quality products. Looking for long term, reliable relationships.'),
(2, 'https://leafedout.com/cannabis-vendor/Colorsound', 'https://leafedout.com/storage/thumbnails/Leafedin_8VBIi0hzdFKBzQuoGNL0wkEVEC0cteSJgsItoFSz.png', 'colorsound', 'colorsound', '5.055555', '299', 'Raleigh, North Carolina', 'Dec 2019', '1059', '$10 for shipping', 'No minimum', 'Flowers, Concentrates, Pre-rolls, Cartridges, Disposables, and Edibles', 'Free shipping on first order', 'Shipping only. I can ship anywhere in USA. You can pay with credit card, Zelle, Venmo, CashApp, PayPal, or Apple Pay.'),
(3, 'https://leafedout.com/cannabis-vendor/big-chief', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-sIMpq0M8e55heR4WT5XfKVwjQIuas0hRCJ0fUkPW.v1704159231.jpeg', 'big chief', 'big-chief', '5.055555', '284', 'Richmond, Virginia', 'Dec 2023', '125', '$10 for shipping', 'No minimum', 'Flowers, Concentrates, Pre-rolls, Cartridges, Disposables, and Edibles', 'Free shipping on first order', 'Shipping only. I can ship anywhere in USA. You can pay with cash, credit card, Zelle, Venmo, CashApp, PayPal, or Apple Pay.'),
(4, 'https://leafedout.com/cannabis-vendor/greenmidas', 'https://leafedout.com/storage/usercontent/pp/LeafedOut-iygoGbfgnZsKDODZgNgRc5Zz66riT91qWOmu2Syl.v1656021774.jpeg', 'greenmidas', 'greenmidas', '5.055555', '277', 'Tampa, Florida', 'Mar 2021', '281', 'NATIONWIDE! In person delivery ???? $2/mile. LONG DISTANCE ???? $15 standard/$30-40 overnight (Shipping)', 'No minimum for pickups. DELIVERY MINIMUM $100 (including delivery fee)', 'MENU IS CURRENT! Click “Show more” on the menu to scroll thru: trees, vapes, dabs, edibles, & more! When you browse my menu, play “I’m too sexy”????????????', 'Mix ‘n’ Match your 1/4, 1/2, or OZ!  Discounts/freebies for regulars! Referral discounts! ALL SALES are NOT final! Issues get RESOLVED! Just ask!', 'Professional connoisseur. “GOAT menu curator”, Quality, Consistency!\nAll sales are NOT final! Issues get RESOLVED! Just ask!');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `menus`
--
ALTER TABLE `menus`
  ADD PRIMARY KEY (`id`),
  ADD KEY `vendor_id` (`vendor_id`);

--
-- Indexes for table `vendors`
--
ALTER TABLE `vendors`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `menus`
--
ALTER TABLE `menus`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=198;

--
-- AUTO_INCREMENT for table `vendors`
--
ALTER TABLE `vendors`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `menus`
--
ALTER TABLE `menus`
  ADD CONSTRAINT `menus_ibfk_1` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
